version: "3.5"

services:
  server:
    container_name: bilemo-caddy
    image: caddy:alpine
    depends_on:
      - backend
    volumes:
      - ./:/app
      - ./system/server/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    labels:
      traefik.enable: true
      traefik.http.routers.snowtricks.rule: Host(`bilemo.anagraph.org`)
    ports:
      - 8000:80

  backend:
    container_name: bilemo-php
    build:
      context: .
      dockerfile: system/backend/Dockerfile
      args:
        PHP_VERSION: "7.4"
    volumes:
      - .:/app
      - ./system/backend/php-custom.ini:/usr/local/etc/php/php.ini

volumes:
  caddy_data:
  caddy_config:

#networks:
#  default:
#    external: true
#    name: proxy